-- what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as total_purchase
from customer
group by gender
order by sum(purchase_amount) desc;

-- which customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount > (select avg(purchase_amount) from customer);

-- what are the top 5 products with the highest average review rating

select item_purchased, round(avg(review_rating)::numeric,2) as "avg_review_rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount)::numeric, 2) as "avg_purchase"
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by avg_purchase desc;

-- do subscribed customers spend more? compare the average spend and total revenue between subscribers and non_subscribers
select subscription_status, 
	count(customer_id) as total_customers,
	round(avg(purchase_amount)::numeric, 2) as  avg_spend, 
	round(sum(purchase_amount)::numeric, 2) as  total_revenue
from customer
where subscription_status in ('Yes', 'No')
group by subscription_status
order by total_customers desc;

-- which 5 products have the highest percentage of purchases with discount applied
select item_purchased, 
100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- segment customers into new, returning and loyal based on their total
-- number of previous purchases showing the count of each segment
with segment as (
select case when previous_purchases = 1 then 'New'
			when previous_purchases between 2 and 10 then 'Returning'
			else 'Loyal'
		end as customer_segment,
customer_id
from customer)
select customer_segment, count(customer_id) as no_of_customers
from segment
group by customer_segment
order by no_of_customers desc;

--what are the top 3 most purchased products within each category
with cte1 as (
select item_purchased, sum(purchase_amount) as total_amount, category
from customer
group by item_purchased, category),
cte2 as(
select category, item_purchased, total_amount,
row_number() over(partition by category order by total_amount desc) as rn
from cte1
)
select category, item_purchased,total_amount, rn
from cte2
where rn <4
order by category, total_amount desc;

-- are customers who are repeat buyers (>5 previous purchases) likely to subscribe??
select  subscription_status, count(customer_id) as customer_count
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age-group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc